export const ADD_SLIDER = 'ADD_SLIDER'
export const ADD_DYNAMIC_ELEMENT = 'ADD_DYNAMIC_ELEMENT'
export const CREATE_DATA = 'CREATE_DATA'
export const CREATE_ANDROID_DATA = 'CREATE_ANDROID_DATA'
export const CREATE_IOS_DATA = 'CREATE_IOS_DATA'

export const NEW_HEADER_ELEMENT = 'NEW_HEADER_ELEMENT'

export const NEW_TEXT_ELEMENT = 'NEW_TEXT_ELEMENT'
export const CLEAR_STORE = 'CLEAR_STORE'
export const CLEAR_PROMO_STORE = 'CLEAR_PROMO_STORE'
export const UPDATE_IMAGE_URLS = 'UPDATE_IMAGE_URLS'
export const ADD_HEADER_ELEMENT = 'ADD_HEADER_ELEMENT'
export const ADD_TEXT_ELEMENT = 'ADD_TEXT_ELEMENT'

export const NEW_BARCODE_ELEMENT = 'NEW_BARCODE_ELEMENT'
export const NEW_BUTTON_ELEMENT = 'NEW_BUTTON_ELEMENT'

export const NEW_IMAGE_ELEMENT = 'NEW_IMAGE_ELEMENT'

